# Default values for your projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Add annotations to the pods
podAnnotations: {}
image:
  repository: nexus-docker.saas-ops.finline.app/q1323829945/test2
  tag: 0.0.2
  pullPolicy: IfNotPresent
# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []
  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true
service:
  name: test2
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  annotations: {}
  # Add labels to the service
  labels: {}
ingress:
  annotations: {}
  # defaults to nginx if no other ingress class annotation specified
  classAnnotation: ""
  # Add labels to the ingress
  labels: {}
  # ingress path type
  pathType: ImplementationSpecific
jxRequirements:
  ingress:
    # shared ingress annotations on all services
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
      kubernetes.io/ingress.class: nginx
    #  kubernetes.io/ingress.class: nginx

    apiVersion: "networking.k8s.io/v1"
    # the domain for hosts
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
